version: 0.2

env:
   parameter-store:
           DB_USER: "/ankit/DB_USER"
           DB_PASSWORD: "/ankit/DB_PASSWORD"
           DB_HOST: "/ankit/DB_HOST"
           DB_NAME: "/ankit/DB_NAME"

phases:
    build:
        commands:
            - sed -i 's/database_name_here/'$DB_NAME'/' wp-config.php
            - sed -i 's/username_here/'$DB_USER'/' wp-config.php
            - sed -i 's/password_here/'$DB_PASSWORD'/' wp-config.php
            - sed -i 's/localhost/'$DB_HOST'/' wp-config.php

artifacts:
        files:
           - '**/*'
        
